services:
  conductor:
    image: orkesio/orkes-conductor-standalone:latest
    ports:
      - "8080:8080"
      - "3000:5000"
    volumes:
      - type: volume
        source: redis
        target: /redis
      - type: volume
        source: postgres
        target: /pgdata
      - type: bind
        source: ./workflows
        target: /app/workflows
    environment:
      - ORKES_ACCESS_KEY=${ORKES_ACCESS_KEY}

volumes:
  redis:
    external: true
  postgres:
    external: true